### PR TITLE
Profile picture feture with `moderncv` theme

### PR DESCRIPTION
**Pull request by kito323**
Only for this theme and only optional "add" possibility. Should also include design parameters (height and frame thickness) but didn't know how to add those so that they would have default values.
Also updated user guide FAQ about it.

### CODE REVIEW

**Comment by kito323** [comment]
Hope this is how it was intended to be updated. Maybe add `design` parameters for the image too. Currently "hard coded" with height of 3.5cm and no frame. Let me know if it works as intended.

**Comment by kito323** [comment]
Okay I can already see that it fails on ubuntu and macos tests and I know why. Because the path for the image uses different dir delimiters and there are libraries that take care of that but how would that be done in the `Preamble.j2.tex` file or are there any good examples in the codebase that I could follow?

**Comment by sinaatalay** [comment]
Thank you! Sorry for the late response.

I think we shouldn't add this feature to RenderCV itself (built-in `Preamble.j2.tex`), as it won't be available for all the themes. Instead, we should write a step-by-step guide in the FAQ that explains how to add profile pictures to any theme. It should basically say: include a path to a photo in the YAML file and update your `Preamble.j2.tex` accordingly (but more detailed, ofc).

**Comment by kito323** [comment]
Reverted the previous commit and only updated FAQ with the instructions of the simplest implementation. If there are too many details, feel free to adjust it.

**Comment by kito323** [comment]
Maybe also linking the two issues to this PR as partial solution or something ([Ability to add a profile photo #28](https://github.com/sinaatalay/rendercv/issues/28) and [Answer an FAQ: Can I add a profile picture? #74](https://github.com/sinaatalay/rendercv/issues/74)). Not sure if I have permissions to do that...

**Comment by sinaatalay** [comment]
Thank you.

**Pull request merged**
